variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "vpc_cidr_blocks" {}
variable "subnet_cidr_blocks" {}
variable "availability_zone" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "instance_type" {}
variable "ssh_public_key_location" {}
variable "image_name" {}